name: Webhook Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v4

    - name: Build the Docker image
      working-directory: ./webhook_server
      run: docker build . --file Dockerfile --tag ghcr.io/axisofentropy/movie-night-webhook:latest

    - name: Push to GitHub Container Registry
      run: docker push ghcr.io/axisofentropy/movie-night-webhook:latest
